### ISSUE TITLE
Switch not controlling light group

### ISSUE THREAD

**Issue by whc-commits** [KaufHA/kauf-rgb-switch#13]
Running the rotate colors and I am unable to get the switch to control the light group. Lights are MQTT and the Kauf switch is esphome.  Turn on/off the switch doesn't switch the bulbs.  Toggling the light group in HA changes the switch state as normal.  Just switch to light group is broken.  No color control, no toggling.  Partial config below.  The light group name in substitutions is correct.
```YAML
substitutions:
  name: cj-room-light
  hass_light_entity: light.cj_room_light_group
  hass_ct_kelvin_fixed: '2300'
  initial_delay: 1000ms

packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml
```

**Comment by bkaufx** [comment]
Do you have the other package in your yaml like in this example: https://github.com/KaufHA/kauf-rgb-switch/tree/main/yaml-features#rotate-colors-sync-to-ha-lightyaml

**Comment by whc-commits** [comment]
Yes - didnt paste the entire block
```YAML
substitutions:
  name: cj-room-light
  hass_light_entity: light.cj_room_light_group
  hass_ct_kelvin_fixed: '2300'
  initial_delay: 1000ms

packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml
  rotate:     github://KaufHA/kauf-rgb-switch/yaml-features/rotate-colors-sync-to-ha-light.yaml 
```
