### ISSUE TITLE
Not showing up as adoptable, also firmware keeps saying the bin is to large.

### ISSUE THREAD

**Issue by wolffman122** [KaufHA/kauf-rgb-switch#2]
Hi so i just installed this device, got it on my network and can get to the switches ip address web interface.  Do not see it as adoptable in esphome, this might because I am running ESPHome in a container and mdns is not playing nice.  Do you know a way to do the adoption by ip address? Or to get it into esphome to rename the device before importing into home assistant?

Secondly trying to update the firmware from 1.2(f) to the 1.32 through the devices web portal.  That keeps failing saying there is not enough space.  Any help would be apperciated.

**Comment by KaufHA** [comment]
You can add use_address under wifi: in the yaml and that will tell ESPHome how to find the device on the network instead of relying on mdns.  That should work.  For the manual bin file, make sure you are using the bin.gz file.  Also, reboot the switch before trying again just in case.

Below is what the yaml should look like.  Just create a new yaml file and paste in the below snippet.  Change the name/friendly name/credentials if necessary/IP address and then it should install fine.

Instead of manually creating a yaml file, you can hit "+ NEW DEVICE" on the dashboard, then click continue, enter in a name, then select ESP8266, and then skip install.  Just "edit" the newly created device, delete everything, and paste in the below yaml.

```
substitutions:
  name: bedroom-light
  friendly_name: Bedroom Light

packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  use_address: 192.168.1.10 # change this to your switch's IP address.
```
