### ISSUE TITLE
Assistant With Linking Small Light to HA Entity : Locked or Unlocked

### ISSUE THREAD

**Issue by jonhaber82** [KaufHA/kauf-rgb-switch#24]
I just installed this RGB switch and have it working with home assistant.

I would like to substitute the bottom small light to reflect the status of my smart lock also in HA.

The states of the lock I see when enabling debugging for my lock is:

2024-12-10 13:28:35.698 DEBUG (MainThread) [homeassistant.components.matter] Lock state: 1 for lock.aqara_smart_lock_u300
2024-12-10 13:28:40.777 DEBUG (MainThread) [homeassistant.components.matter] Lock state: 2 for lock.aqara_smart_lock_u300

this is my current yaml updates which is not working : kauf-rgbsw-5116d9.yaml

```
substitutions:
  name: kauf-rgbsw-5116d9
  friendly_name: firePlaceLight
  hass_entity_control_small_light: lock.aqara_smart_lock_u300
  hhass_entity_control_small_light_on_state: '2'
  hass_entity_control_small_light_off_state: '1'
packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs-4m.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false 
api:
  encryption:
    key: ow9rlZL8v+tZBOXl8Ttyxqt/WyWutx5i0uNDRkyA5Dw=
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
``` 

and my switch device config:
<img width="302" alt="Screenshot 2024-12-10 at 1 42 22 PM" src="https://github.com/user-attachments/assets/bd79c16e-cec2-4b57-89b9-57735cdd78c5">

thanks!

**Comment by bkaufx** [comment]
For one you may have a typo with two h's at the beginning of the on state.

Check the logs on the home assistant device and see if there is a text sensor called hass_small_light_state that prints out every time that entity value changes.  The substitution values need to match that.

**Comment by jonhaber82** [comment]
thank you!

got it working

posting the change in case anyone finds this thread in the future

```
substitutions:
  name: kauf-rgbsw-5116d9
  friendly_name: firePlaceLight
  hass_entity_control_small_light: lock.aqara_smart_lock_u300
  hass_entity_control_small_light_on_state: 'unlocking'
  hass_entity_control_small_light_off_state: 'locking'
```
