### ISSUE TITLE
Disable All Button Actions Except Bulb Power Toggle

### ISSUE THREAD

**Issue by jonhaber82** [KaufHA/kauf-rgb-switch#25]
Following up from my post the other day, I am trying to use the kaufrgbswitch to control a ceiling light and use the small light as an indicator when a HASS entity state changes. Unfortunately, it is still not working as expected.

**Situation / Desired Functionality:**

**Button & Big Light**
- The button should turn a wired non-smart bulb on and off.
- The button hold or double press actions will not be used.
- The buttons physical use should have **no impact at all on the big light or small light**.

**Small Light**
- I am using two HASS automations to check when an entity binary state changes (i.e., 'locked' and 'unlocked').
- When the entity state is changed to a specific value ('locked') the small light should show a red light.
- When the entity state is changed to a specific value ('unlocked') the small light should turn off.

The automations are working as expected; however, **the use of the button impacts the functions of the small light**.

I tried editing my kauf-rgbsw yaml substitutions for actions without success.

**Current Config & Settings**
_All controls, sensors, configurations are set to off unless noted below_

- ceilingLight 4MiB: ON
- ceilingLight Button Config : Toggle on Press
- ceilingLight No HASS: ON
- ceilingLight Relay Config: Switched

**Current kauf-rgbsw-5116d9.yaml**

```
substitutions:
  name: kauf-rgbsw-5116d9
  friendly_name: ceilingLight
  disable_entities: "false" 
  sub_on_press: script_do_nothing
  sub_on_release: script_do_nothing
  sub_on_double_press: script_do_nothing
  sub_on_single_press: script_do_nothing
  sub_on_hold: script_do_nothing
  sub_on_release_without_hold: script_do_nothing
  sub_toggle_check: script_do_nothing
  sub_on_turn_on: script_do_nothing
  sub_on_turn_off: script_do_nothing
packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs-4m.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false 
api:
  encryption:
    key: XXXXXX
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
``` 

Any and all help is much appreciated in resolving/configuring the switch as described above.
Thanks!
