### ISSUE TITLE
Relay Changes to 'Always On' After Power Cycle

### ISSUE THREAD

**Issue by sbailey151** [KaufHA/kauf-rgb-switch#28]
Every time my power goes out, 2 of my switch's relays default to 'Always On'.  This does not happen with my other Kauf RGB Switches, just the 2 newest ones.  Before I setup some automation in HA to flip it back each time, is there a reason why this is only affecting 2 of my switches?  Below is the YAML I am using for one of the 2 switches.

```
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: "Game Room Light Switch"

substitutions:
  name: game-room-light-switch
  sub_wifi_reset_script: script_do_nothing

packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs-4m.yaml
  rotate_colors: github://KaufHA/kauf-rgb-switch/yaml-features/rotate-colors-sync-to-ha-light.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
