### ISSUE TITLE
How to use configuration?

### ISSUE THREAD

**Issue by michaelkamprath** [KaufHA/kauf-rgb-switch#7]
So I am sure this is a totally n00b question, but how do I use the [rotate-colors-sync-to-ha-light.yaml](https://github.com/KaufHA/kauf-rgb-switch/blob/main/yaml-features/rotate-colors-sync-to-ha-light.yaml) configuration in home assistant. I placed the indicated `packages:` YAML in my Home Assistant `configuration.yaml` file, but Home Assistant puked all of it.  So I am sure I am totally missing something. Ultimately, I want to trigger the color cycling and generally set the LED color to use that as a sort of indicator.

Thanks for any pointers.

**Comment by bkaufx** [comment]
It needs to be in the ESPHome configuration yaml file for the particular switch.  Do you have the ESPHome dashboard installed?

**Comment by michaelkamprath** [comment]
Ah, I did not know that existed (I would suggest making this clearer in your documentation). So I looked into ESPHome, got it installed, but it says "A device needs to be connected to a computer using a USB cable to be added to ESPHome". How am I supposed to do that with the wall switch, especially once it is installed in the wall?

**Comment by bkaufx** [comment]
If the ESPHome dashboard isn't giving you the option to adopt the switch after detecting it automatically, then just create a new device and use the following yaml.  You can just manually create a yaml file or create a device through the dashboard UI.  When creating a device in the dashboard UI, the options don't matter since you are going to completely erase the auto-generated yaml and paste in the below yaml instead.

Change the use_address to the ip address of the switch, flash/install, and then remove the use_address line.

```
substitutions:
  name: bedroom-light
  friendly_name: Bedroom Light

packages:
  rotate_colors: github://bkaufx/kauf-rgb-switch/yaml-features/rotate-colors-sync-to-ha-light.yaml
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  use_address: 192.168.1.24
```
